spring.application.name=birthday_reminder

# ===============================
# CHANGE TOMCAT PORT IF NEEDED
# ===============================
#server.port=8082  



# ===============================
# DATABASE CONNECTION
# ===============================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# ===============================
# JPA / HIBERNATE
# Hibernate ddl auto (create, create-drop, validate, update)
# ===============================

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto = update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect



#==================
#SMTP PROPERTIES
#================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASS}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



